"""The deterministic warning baseline (PLAN.md 6.7).

This is the floor. It runs every tick, it is plain arithmetic over the zone
assessment, and its reasons are generated by code with the numbers in them. The
agent reasons *over* this baseline and may raise it; it can never lower it, and
if the agent is unavailable this is what ships to screen.

Keeping the rules here, rather than in a prompt, is what makes the system's core
safety property checkable: a hostile field report cannot argue its way past
arithmetic.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Mapping, Sequence

from goru_core.config import Config
from goru_core.schemas import Level, TrackState, ZoneAssessment

__all__ = ["BaselineVerdict", "ReportSupport", "RuleEngine", "Hysteresis"]

HEAVY_CLASSES = frozenset({"truck", "bus"})


@dataclass(frozen=True)
class ReportSupport:
    """What the field reports alone may justify for one track (PLAN 6.8.5)."""

    cap: Level = Level.CLEAR
    report_ids: tuple[str, ...] = ()
    note: str | None = None


@dataclass(frozen=True)
class BaselineVerdict:
    """The rule engine's output for one track."""

    level: Level
    zone_id: str | None
    priority: float
    reasons: list[str] = field(default_factory=list)
    evidence: list[str] = field(default_factory=list)
    destination_zone_id: str | None = None


class RuleEngine:
    """Evaluates the ALERT / WATCH / CLEAR table for a track against its zones."""

    def __init__(self, cfg: Config, zone_names: Mapping[str, str]) -> None:
        self._cfg = cfg
        self._zone_names = dict(zone_names)

    def _name(self, zone_id: str | None) -> str:
        return self._zone_names.get(zone_id or "", zone_id or "unknown")

    def evaluate(
        self,
        state: TrackState,
        assessments: Sequence[ZoneAssessment],
        *,
        detection_id: str | None = None,
        report_support: ReportSupport | None = None,
        destination_zone_id: str | None = None,
    ) -> BaselineVerdict:
        """Level, priority and human-readable reasons for one track."""
        warning = self._cfg.warning
        support = report_support or ReportSupport()
        heavy = state.class_hint in HEAVY_CLASSES
        reasons: list[str] = []
        evidence: list[str] = [state.track_id]
        if detection_id:
            evidence.append(detection_id)
        evidence.extend(support.report_ids)

        # Collect every rule that fires, then pick the level and the zone that
        # drives it. Picking afterwards means the displayed zone is the most
        # urgent one, not merely the first in the list.
        triggers: list[tuple[Level, ZoneAssessment, str]] = []
        for assessment in assessments:
            zone_name = self._name(assessment.zone_id)

            if assessment.inside_zone:
                triggers.append(
                    (
                        Level.ALERT,
                        assessment,
                        f"inside {zone_name}: {assessment.dist_now_m:.0f} m from its centre",
                    )
                )
                continue

            eta = assessment.eta_entry_s
            if (
                eta is not None
                and eta <= warning.alert_eta_s
                and assessment.approach_conf >= warning.alert_conf
            ):
                triggers.append(
                    (
                        Level.ALERT,
                        assessment,
                        f"ETA {eta / 60.0:.1f} min to {zone_name} at {state.speed_mps:.1f} m/s, "
                        f"approach {assessment.approach_conf:.2f}",
                    )
                )
                continue

            if assessment.inside_buffer:
                triggers.append(
                    (
                        Level.WATCH,
                        assessment,
                        f"inside the buffer of {zone_name}: {assessment.dist_now_m:.0f} m out",
                    )
                )
                continue

            if (
                assessment.cpa_m <= self._radius_plus_buffer(assessment)
                and 0.0 < assessment.t_cpa_s <= warning.horizon_s
                and assessment.approach_conf >= warning.watch_conf
            ):
                triggers.append(
                    (
                        Level.WATCH,
                        assessment,
                        f"CPA {assessment.cpa_m:.0f} m to {zone_name} in "
                        f"{assessment.t_cpa_s / 60.0:.1f} min, approach {assessment.approach_conf:.2f}",
                    )
                )

        level = Level.highest(*(lv for lv, _, _ in triggers))
        at_level = [(a, why) for lv, a, why in triggers if lv is level]
        driving: ZoneAssessment | None = None
        if at_level:
            driving = min(
                at_level,
                key=lambda pair: (
                    pair[0].eta_entry_s if pair[0].eta_entry_s is not None else float("inf"),
                    pair[0].dist_now_m,
                ),
            )[0]
            reasons.extend(why for _, why in at_level)

        # Reports may raise, never lower, and only up to their own cap.
        if support.cap.rank > level.rank:
            level = support.cap
            reasons.insert(
                0, support.note or f"field report evidence ({', '.join(support.report_ids)})"
            )

        if level is Level.CLEAR and not reasons:
            nearest = min(assessments, key=lambda a: a.dist_now_m, default=None)
            if nearest is not None:
                reasons.append(
                    f"nearest zone {self._name(nearest.zone_id)} is {nearest.dist_now_m:.0f} m away; "
                    f"{'stationary' if state.stationary else f'{state.speed_mps:.1f} m/s'}"
                )

        priority = self._priority(driving, state, heavy=heavy)
        return BaselineVerdict(
            level=level,
            zone_id=driving.zone_id if driving else None,
            priority=priority,
            reasons=reasons[:4],
            evidence=evidence,
            destination_zone_id=destination_zone_id,
        )

    def _radius_plus_buffer(self, assessment: ZoneAssessment) -> float:
        cfg = self._cfg.zones
        name = self._zone_names.get(assessment.zone_id, "")
        return cfg.radius_for(name) + cfg.buffer_for(name)

    def _priority(
        self, assessment: ZoneAssessment | None, state: TrackState, *, heavy: bool
    ) -> float:
        """0..1 ranking within a level (PLAN 6.7); heavy vehicles are weighted up."""
        if assessment is None:
            return 0.0
        warning = self._cfg.warning
        eta = assessment.eta_entry_s
        eta_term = 1.0 - min(1.0, (eta if eta is not None else warning.horizon_s) / warning.horizon_s)
        span = self._radius_plus_buffer(assessment)
        cpa_term = 1.0 - min(1.0, assessment.cpa_m / span if span > 0 else 1.0)
        score = 0.5 * eta_term + 0.3 * cpa_term + 0.2 * assessment.approach_conf
        if heavy:
            score *= warning.heavy_vehicle_multiplier
        return float(min(1.0, max(0.0, score)))

    def untracked_detection_level(self, inside_buffer: bool) -> Level:
        """An untracked detection inside a buffer is a WATCH; otherwise CLEAR."""
        return Level.WATCH if inside_buffer else Level.CLEAR


class Hysteresis:
    """Upgrades apply at once; downgrades need N consecutive quieter ticks (PLAN 6.7).

    Without this, a vehicle hovering at a threshold flickers between levels and
    the queue becomes unreadable.
    """

    def __init__(self, consecutive: int) -> None:
        self._needed = max(1, consecutive)
        self._current: dict[str, Level] = {}
        self._pending: dict[str, tuple[Level, int]] = {}

    def apply(self, key: str, proposed: Level) -> Level:
        current = self._current.get(key)
        if current is None or proposed.rank >= current.rank:
            self._current[key] = proposed
            self._pending.pop(key, None)
            return proposed

        pending_level, count = self._pending.get(key, (proposed, 0))
        count = count + 1 if pending_level is proposed else 1
        if count >= self._needed:
            self._current[key] = proposed
            self._pending.pop(key, None)
            return proposed
        self._pending[key] = (proposed, count)
        return current

    def level_of(self, key: str) -> Level:
        return self._current.get(key, Level.CLEAR)

    def reset(self) -> None:
        self._current.clear()
        self._pending.clear()
